backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "news"
    label: "お知らせ"
    folder: "_news"
    create: true
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "カテゴリ", name: "category", widget: "select", options: ["お知らせ", "イベント", "活動報告"]}
      - {label: "本文", name: "body", widget: "markdown"}
